######################## default configuration ####################
baseURL = "https://ChrisLinOvO.github.io"
languageCode = "zh-tw"
title = "Chris Lin's Blog"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "About Me"
URL = "about/"
weight = 1

[[menu.main]]
name = "Old Website"
URL = "https://chrislinovo.github.io/blog/"
weight = 2

# footer menu
[[menu.footer]]
name = "About"
URL = "about/"
weight = 1

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "I am a software engineer with more than 3 years of experience."
author = "Chris"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "0925013186"
email = "qq2120621@gmail.com"
location = "Taiwan"
# copyright
copyright = "| copyright &copy; 2021 [Themefisher](https://themefisher.com/hugo-themes/) All Rights Reserved |"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/ChrisLinOvO"

[[params.social]]
title = "email"
icon = "ti-email"
link = "mailto:qq2120621@gmail.com"
